package com.dspot.declex.wrapper.generate;

import org.androidannotations.AndroidAnnotationsEnvironment;
import org.androidannotations.internal.generation.CodeModelGenerator;

public class DeclexCodeModelGenerator extends CodeModelGenerator {

	public DeclexCodeModelGenerator(String aaVersion, String encoding, AndroidAnnotationsEnvironment env) {
		super(env.getProcessingEnvironment().getFiler(), aaVersion, encoding);
		header = "DO NOT EDIT THIS FILE. Generated using DSpot Sp. z o.o - DecleX " + aaVersion + " "
				+ "and AndroidAnnotations .\n " + 
				"You can create a larger work that contains this file and distribute that work under terms of your choice.\n";
	}
	
}
