/**
 * Copyright (C) 2016-2017 DSpot Sp. z o.o
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *    http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.dspot.declex;

import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.PrintStream;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import javax.annotation.processing.RoundEnvironment;
import javax.lang.model.element.AnnotationMirror;
import javax.lang.model.element.Element;
import javax.lang.model.element.ElementKind;
import javax.lang.model.element.TypeElement;
import javax.lang.model.type.TypeMirror;

import org.androidannotations.annotations.Bean;
import org.androidannotations.handler.AnnotationHandler;
import org.androidannotations.helper.AndroidManifest;
import org.androidannotations.internal.generation.CodeModelGenerator;
import org.androidannotations.internal.helper.AndroidManifestFinder;
import org.androidannotations.internal.model.AnnotationElements;
import org.androidannotations.internal.model.AnnotationElements.AnnotatedAndRootElements;
import org.androidannotations.internal.model.AnnotationElementsHolder;
import org.androidannotations.internal.model.ModelExtractor;
import org.androidannotations.internal.process.ModelProcessor.ProcessResult;
import org.androidannotations.logger.Logger;
import org.androidannotations.logger.LoggerContext;
import org.androidannotations.logger.LoggerFactory;
import org.androidannotations.plugin.AndroidAnnotationsPlugin;

import com.dspot.declex.action.Actions;
import com.dspot.declex.annotation.Export;
import com.dspot.declex.annotation.External;
import com.dspot.declex.annotation.Import;
import com.dspot.declex.annotation.JsonModel;
import com.dspot.declex.annotation.LocalDBModel;
import com.dspot.declex.annotation.ServerModel;
import com.dspot.declex.annotation.UseEvents;
import com.dspot.declex.annotation.UseModel;
import com.dspot.declex.annotation.action.ActionFor;
import com.dspot.declex.api.util.FormatsUtils;
import com.dspot.declex.helper.ActionHelper;
import com.dspot.declex.helper.FilesCacheHelper;
import com.dspot.declex.helper.FilesCacheHelper.FileDetails;
import com.dspot.declex.parser.LayoutsParser;
import com.dspot.declex.parser.MenuParser;
import com.dspot.declex.util.DeclexConstant;
import com.dspot.declex.util.SharedRecords;
import com.dspot.declex.util.TypeUtils;
import com.dspot.declex.wrapper.RoundEnvironmentByCache;
import com.dspot.declex.wrapper.element.VirtualElement;
import com.dspot.declex.wrapper.generate.DeclexCodeModelGenerator;
import com.helger.jcodemodel.IJExpression;
import com.helger.jcodemodel.JExpr;
import com.helger.jcodemodel.JFieldRef;
import com.sun.source.tree.IdentifierTree;
import com.sun.source.tree.ImportTree;
import com.sun.source.util.TreePath;
import com.sun.source.util.TreePathScanner;
import com.sun.source.util.Trees;

public class DeclexProcessor extends org.androidannotations.internal.AndroidAnnotationProcessor {
	
	private static final boolean PRE_GENERATION_ENABLED = true;
	
	private static final Logger LOGGER = LoggerFactory.getLogger(DeclexProcessor.class);
	
	protected LayoutsParser layoutsParser;
	protected MenuParser menuParser;
	protected Actions actions;
	
	protected FilesCacheHelper filesCacheHelper;
	protected Set<FileDetails> cachedFiles;
	protected int cachedFilesGenerated;
	
	@Override
	protected AndroidAnnotationsPlugin getCorePlugin() {
		return new DeclexCorePlugin();
	}
	
	@Override
	protected String getFramework() {
		return "DecleX";
	}
	
	@Override
	protected void helpersInitialization() {
		super.helpersInitialization();
		
		try {
			timeStats.start("Helpers Initialization");
						
			layoutsParser = new LayoutsParser(androidAnnotationsEnv, LOGGER);
			menuParser = new MenuParser(androidAnnotationsEnv, LOGGER);
			
			actions = new Actions(androidAnnotationsEnv);	
			
			filesCacheHelper = new FilesCacheHelper(androidAnnotationsEnv);
			cachedFiles = new HashSet<>();
			
			if (FilesCacheHelper.isCacheFilesEnabled()) {
				cachedFiles.addAll(filesCacheHelper.getAutogeneratedClasses()); //Write all Cached Autogenerated Classes
				cachedFilesGenerated = 0;
				
				if (PRE_GENERATION_ENABLED) {
					for (FileDetails details : cachedFiles) {
						if (!details.canBeUpdated) {
							details.preGenerate(androidAnnotationsEnv);
						}
					}
				}
				
			}
			
			timeStats.stop("Helpers Initialization");
			timeStats.logStats();
			
		} catch (Throwable e) {
			System.err.println("Something went wrong starting the framework");
			e.printStackTrace();
		}
	}
		
	@Override
	public boolean process(Set<? extends TypeElement> annotations,
			RoundEnvironment roundEnv) {
		
		LOGGER.info("Executing Declex");
						
		try {

			return super.process(annotations, roundEnv);
			
		} catch (Throwable e) {
			LOGGER.error("An error occured", e);
			LoggerContext.getInstance().close(true);
			
			e.printStackTrace();
			
			return false;
		}
		
	}
	
	@Override
	protected boolean nothingToDo(Set<? extends TypeElement> annotations,
			RoundEnvironment roundEnv) {		
		
		boolean nothingToDo = super.nothingToDo(annotations, roundEnv);
		
		if (nothingToDo) {			
			if (roundEnv.processingOver()) {
			
				timeStats.start("Writing Cache");
				
				long time = 0;
				//Wait till all the documents be saved
				while (FileDetails.isSaving()) {
					
					if (time > 30000) {
						LOGGER.error("Timeout writing to Cache for more than 30 segs");
						break;
					}
					
					try {
						Thread.sleep(100);
						time += 100;
					} catch (InterruptedException e) {};
				}
				
				if (FileDetails.getFailedGenerations().size() > 0) {
					LOGGER.error("Generation of Cached Files Failed with " + FileDetails.getFailedGenerations());
				}
				
				filesCacheHelper.saveGeneratedClasses();
				
				filesCacheHelper.ensureSources();
				
				timeStats.stop("Writing Cache");
			}
			
			return true;
		} else {

			try {
				boolean libraryOption = androidAnnotationsEnv.getOptionBooleanValue(AndroidManifestFinder.OPTION_LIBRARY);
				if (libraryOption) {
					final AndroidManifest androidManifest = new AndroidManifestFinder(androidAnnotationsEnv).extractAndroidManifest();
					final String libraryPackage = androidManifest.getApplicationPackage(); 
					
					DeclexConstant.ACTION = libraryPackage + ".Action";
					DeclexConstant.EVENT_PATH = libraryPackage + ".event.";
				}
			} catch (Exception e) {}
			
			//Update actions information in each round
			timeStats.start("Update Actions");
			actions.getActionsInformation();		
			timeStats.stop("Update Actions");
		}
		
		return false;
	}
	
	@Override
	protected AnnotationElementsHolder extractAnnotations(
			Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
		
		if (!FilesCacheHelper.isCacheFilesEnabled()) {
			timeStats.start("Scan for Exports");
			Map<TypeElement, Set<? extends Element>> virtualAnnotatedElements = new HashMap<>();
			scanForExports(roundEnv, annotations, virtualAnnotatedElements);
			timeStats.stop("Scan for Exports");
			
			timeStats.start("Extract Annotations");
			
			final ModelExtractor modelExtractor = new ModelExtractor();
			final AnnotationElementsHolder extractedModel;
			
			if (!virtualAnnotatedElements.isEmpty()) {				
				
				Set<TypeElement> completeAnnotations = new HashSet<>(annotations);
				completeAnnotations.addAll(virtualAnnotatedElements.keySet());
				
				for (TypeElement annotation : annotations) {
					Set<? extends Element> elements = roundEnv.getElementsAnnotatedWith(annotation);
					if (virtualAnnotatedElements.containsKey(annotation)) {
						
						Set virtualElements = virtualAnnotatedElements.get(annotation);						
						for (Element element : elements) {
							virtualElements.add(element);	
						}
						
					} else {
						virtualAnnotatedElements.put(annotation, elements);
					}
				}
				
				
				extractedModel = modelExtractor.extract(
						completeAnnotations, 
					getSupportedAnnotationTypes(), 
					new RoundEnvironmentByCache(roundEnv, virtualAnnotatedElements)
				);
				
			} else {
				extractedModel = modelExtractor.extract(annotations, getSupportedAnnotationTypes(), roundEnv);
			}
			
			Set<AnnotatedAndRootElements> ancestorAnnotatedElements = extractedModel.getAllAncestors();
			for (AnnotatedAndRootElements elements : ancestorAnnotatedElements) {
				
				//Add ancestors to File Cache Service
				Element rootElement = elements.annotatedElement;
				if (rootElement.getEnclosingElement().getKind().equals(ElementKind.PACKAGE)) {					
					FilesCacheHelper.getInstance().addAncestor(rootElement, elements.rootTypeElement);
				}
			}
			
			timeStats.stop("Extract Annotations");
			
			return extractedModel;
									
		}
		
		//TODO The Cache service is not prepared for Exports and Externals
		
		timeStats.start("Extract Annotations");
		
		Map<TypeElement, Set<? extends Element>> annotatedElements = new HashMap<>();
		Set<TypeElement> noCachedAnnotations = new HashSet<>();
		
		Set<String> confirmedCachedClasses = new HashSet<>();
		Map<String, Boolean> confirmedAncestorsClasses = new HashMap<>();
		
		for (TypeElement annotation : annotations) {
			Set<? extends Element> elements = roundEnv.getElementsAnnotatedWith(annotation);
									
			Set<Element> annotatedElementsWithAnnotation = new HashSet<>();			
			
			annotationElements: for (Element element : elements) {
					
				final Element rootElement = TypeUtils.getRootElement(element);		
				final String rootElementClass = rootElement.asType().toString();
				
				if (confirmedAncestorsClasses.containsKey(rootElementClass)) {
					if (confirmedAncestorsClasses.get(rootElementClass)) {
						annotatedElementsWithAnnotation.add(element);
					}
					continue;
				}
				
				if (filesCacheHelper.isAncestor(rootElementClass)) {
										
					Set<String> subClasses = filesCacheHelper.getAncestorSubClasses(rootElementClass);
					for (String subClass : subClasses) {
						
						if (filesCacheHelper.isAncestor(subClass)) continue;
						
						//TODO
						//Only direct generated classes are checked for cache, but there's others generated classes
						//which are not checked, for instance the Events and Actions Holders, even if their cache
						//is invalid this mechanism doesn't guarantee to regenerate them
						final String generatedSubClassName = TypeUtils.getGeneratedClassName(subClass, androidAnnotationsEnv, false);
						
						if (!filesCacheHelper.hasCachedFile(generatedSubClassName)) {
							annotatedElementsWithAnnotation.add(element);
							
							confirmedAncestorsClasses.put(rootElementClass, true);
							continue annotationElements;
						}
					}
					
					confirmedAncestorsClasses.put(rootElementClass, false);
					continue;
				}
				
				//Get Generated Class Name for the rootElement				
				//TODO
				//Only direct generated classes are checked for cache, but there's others generated classes
				//which are not checked, for instance the Events and Actions Holders, even if their cache
				//is invalid this mechanism doesn't guarantee to regenerate them
				final String generatedClassName = TypeUtils.getGeneratedClassName(rootElement, androidAnnotationsEnv);
				if (confirmedCachedClasses.contains(generatedClassName)) continue;
				
				
				if (filesCacheHelper.hasCachedFile(generatedClassName)) {

					Set<FileDetails> detailsList = filesCacheHelper.getFileDetailsList(generatedClassName);
					for (FileDetails details : detailsList) {						
						cachedFiles.add(details);
						
						if (PRE_GENERATION_ENABLED && !details.canBeUpdated) {
							details.preGenerate(androidAnnotationsEnv);
						}
					}
					
					confirmedCachedClasses.add(generatedClassName);
					
				} else {
					annotatedElementsWithAnnotation.add(element);
				}
			}
			
			if (!annotatedElementsWithAnnotation.isEmpty()) {
				noCachedAnnotations.add(annotation);
				annotatedElements.put(annotation, annotatedElementsWithAnnotation);
			}
		}
		
		if (PRE_GENERATION_ENABLED) {
			filesCacheHelper.preGenerateSources();
		}
		
		ModelExtractor modelExtractor = new ModelExtractor();
		AnnotationElementsHolder extractedModel = modelExtractor.extract(
			noCachedAnnotations, 
			getSupportedAnnotationTypes(), 
			new RoundEnvironmentByCache(roundEnv, annotatedElements)
		);
				
		Set<AnnotatedAndRootElements> ancestorAnnotatedElements = extractedModel.getAllAncestors();
		for (AnnotatedAndRootElements elements : ancestorAnnotatedElements) {
			
			//Add ancestors to File Cache Service
			Element rootElement = elements.annotatedElement;
			if (rootElement.getEnclosingElement().getKind().equals(ElementKind.PACKAGE)) {
				FilesCacheHelper.getInstance()
				                .addAncestor(rootElement, elements.rootTypeElement);
			}
		}
		
		timeStats.stop("Extract Annotations");
				
		return extractedModel;
	}
	
	/**
	 * This method scans all the compilation units of generating annotations searching 
	 * for Actions and Beans which export methods. It creates Virtual Elements for these
	 * exported methods
	 * @param roundEnv
	 * @param annotations 
	 * @param virtualAnnotatedElements 
	 */
	private void scanForExports(RoundEnvironment roundEnv, Set<? extends TypeElement> annotations, 
			final Map<TypeElement, Set<? extends Element>> virtualAnnotatedElements) {
	
		//TODO find the best way to call the annotation dependency injection, the method below is a simple hack
		Set<String> generatingTargets = new HashSet<>();
		Set<Element> processedElements = new HashSet<>();
		{
			for (AnnotationHandler<?> annotationHandler : androidAnnotationsEnv.getGeneratingHandlers()) {
				generatingTargets.add(annotationHandler.getTarget());
			}
			
			generatingTargets.add(External.class.getCanonicalName());
			generatingTargets.add(UseModel.class.getCanonicalName());
			generatingTargets.add(UseEvents.class.getCanonicalName());
			generatingTargets.add(LocalDBModel.class.getCanonicalName());
			generatingTargets.add(JsonModel.class.getCanonicalName());
			generatingTargets.add(ServerModel.class.getCanonicalName());
		}
		
		//Import exported methods
		for (String generatingTarget : generatingTargets) {
			
			final TypeElement annotation = processingEnv.getElementUtils().getTypeElement(generatingTarget);
			final Set<? extends Element> elements = roundEnv.getElementsAnnotatedWith(annotation);
						
			//Check all the actions
			for (final Element element : elements) {
				
				if (!element.getKind().isClass()) continue;
				
				if (processedElements.contains(element)) continue;
				processedElements.add(element);
				
				final Trees trees = Trees.instance(processingEnv);
		    	final TreePath treePath = trees.getPath(element);	
		    	
		    	boolean actionScanNeeded = false;
		    	for (ImportTree importTree : treePath.getCompilationUnit().getImports()) {
		    	
		            if (Actions.isAction(importTree.getQualifiedIdentifier().toString())) {
		            	actionScanNeeded = true;
		            	
		            	//The loop continues in order to check different libraries actions  
		            } 
		            
		    	}		    	
		    			    	
		    	if (actionScanNeeded) {
		    		
	            	for (Element elem : element.getEnclosedElements()) {
	            		
	            		final TreePath elemTreePath = trees.getPath(elem);
	            		
    	            	TreePathScanner<Boolean, Trees> scanner = new TreePathScanner<Boolean, Trees>() {
    	            		@Override
    	            		public Boolean visitIdentifier(IdentifierTree id, Trees trees) {
    	            			
    	            			String name = id.getName().toString();
    	            			
    	            			if (Actions.getInstance().hasActionNamed(name)) {
    	            				TypeElement actionHolderElement = Actions.getInstance().getActionHolderForAction(name);
    	            				final ActionFor actionForAnnotation = actionHolderElement.getAnnotation(ActionFor.class);
    	            				
    	            				//Only global actions can export methods
    	            				if (actionForAnnotation.global()) {
    	            					
    	            					final int position = (int) trees.getSourcePositions()
    	            							                        .getStartPosition(treePath.getCompilationUnit(), id);				
    	            					final String actionName = name.substring(0, 1).toLowerCase() + name.substring(1) + position;	
    	            					
    	            					scanForExports(
    	            							actionHolderElement, 
    	            							(TypeElement)element, 
    	            							null,
    	            							JExpr.ref(actionName),
    	            							JExpr.ref(actionName), 
    	            							virtualAnnotatedElements,
    	            							false);
    	            				}
    	            			}
    	            			
    	            			return super.visitIdentifier(id, trees);
    	            		}
    	            	};
    	            	scanner.scan(elemTreePath, trees);
	            				            		
	            	} //for
		    	} //if (actionScanNeeded)
		    	
		    	//Scan all the Beans used
            	for (Element elem : element.getEnclosedElements()) {
            		if (elem.getKind().isField() && elem.getAnnotation(Bean.class) != null) {
	            		TypeElement typeElement = processingEnv.getElementUtils().getTypeElement(elem.asType().toString());
	            		
	            		if (typeElement != null) {

	            			JFieldRef beanReference = JExpr.ref(elem.getSimpleName().toString());
	            			IJExpression castedBeanReference = JExpr.cast(
	            					androidAnnotationsEnv.getJClass(TypeUtils.getGeneratedClassName(typeElement, androidAnnotationsEnv)), beanReference);
	            			
        					scanForExports(
        							typeElement, (TypeElement)element, elem,
        							beanReference, castedBeanReference, virtualAnnotatedElements, true);
	            		}
	            	}
            	}
			}
		}
	}
	
	private void scanForExports(
			TypeElement element, TypeElement enclosingElement, Element referenceElement,
			IJExpression referenceExpression,  IJExpression castedReferenceExpression,
			Map<TypeElement, Set<? extends Element>> virtualAnnotatedElements,
			boolean castToForward) {
		
		for (Element elem : element.getEnclosedElements()) {

			Export exportAnnotation = elem.getAnnotation(Export.class);
			Import importAnnotation = elem.getAnnotation(Import.class);
			if (exportAnnotation != null || importAnnotation != null) {
				
				if (elem.getKind() == ElementKind.METHOD) {
						
					//This element should be exported
					VirtualElement virtualElement = VirtualElement.from(elem);
					virtualElement.setEnclosingElement(enclosingElement);
					virtualElement.setReference(referenceElement);
					
					if (importAnnotation != null) {
						virtualElement.setReferenceExpression(castedReferenceExpression);
					} else {
						virtualElement.setReferenceExpression(referenceExpression);	
					}					
					
					for (AnnotationMirror annotation : virtualElement.getAnnotationMirrors()) {
						
						if (androidAnnotationsEnv.getSupportedAnnotationTypes().contains(annotation.getAnnotationType().toString())) {
							TypeElement annotationType = (TypeElement) annotation.getAnnotationType().asElement();
								
							Set elements = virtualAnnotatedElements.get(annotationType);							
							if (elements == null) {
								elements = new HashSet<>();
								virtualAnnotatedElements.put(annotationType, elements);
							}
							
							elements.add(virtualElement);
						}	
						
					}						
				}
				
				//Scan exported subfields beans
				if (elem.getKind().isField() && elem.getAnnotation(Bean.class) != null) {
					TypeElement typeElement = processingEnv.getElementUtils().getTypeElement(elem.asType().toString());
            		
					IJExpression forwardExpression;
					if (castToForward) {
						forwardExpression = 
								JExpr.cast(androidAnnotationsEnv.getJClass(TypeUtils.getGeneratedClassName(element, androidAnnotationsEnv)), referenceExpression)
								     .invoke(FormatsUtils.fieldToGetter(elem.getSimpleName().toString()));
					} else {
						forwardExpression = referenceExpression.invoke(FormatsUtils.fieldToGetter(elem.getSimpleName().toString()));
					}
					
            		if (typeElement != null) {
    					scanForExports(
    							typeElement, 
    							enclosingElement, 
    							referenceElement,
    							forwardExpression,
    							castedReferenceExpression.invoke(FormatsUtils.fieldToGetter(elem.getSimpleName().toString())),
    							virtualAnnotatedElements, 
    							true);
            		}
				}
			}

		}
		
		List<? extends TypeMirror> superTypes = processingEnv.getTypeUtils().directSupertypes(element.asType());
		for (TypeMirror type : superTypes) {
			TypeElement superElement = processingEnv.getElementUtils().getTypeElement(type.toString());
			if (superElement == null) continue;
			if (superElement.getKind().equals(ElementKind.INTERFACE)) continue;
			if (superElement.asType().toString().equals(Object.class.getCanonicalName())) break;
			
			scanForExports(
					superElement, enclosingElement, referenceElement,
					referenceExpression, castedReferenceExpression, 
					virtualAnnotatedElements, castToForward);
		}
		
	}
	
	@Override
	protected AnnotationElements validateAnnotations(
			AnnotationElements extractedModel,
			AnnotationElementsHolder validatingHolder) {
		
		filesCacheHelper.validateCurrentCache();
		
		AnnotationElements annotationElements = super.validateAnnotations(extractedModel, validatingHolder);
		
		//Run validations for Actions (it should be run after all the normal validations)
		timeStats.start("Validate Actions");
		LOGGER.info("Validating Actions");
		ActionHelper.getInstance(androidAnnotationsEnv).validate();
		timeStats.stop("Validate Actions");
		
		return annotationElements;
	}
	
	@Override
	protected ProcessResult processAnnotations(AnnotationElements validatedModel)
			throws Exception {
		
		ProcessResult result = super.processAnnotations(validatedModel);
		
		SharedRecords.priorityExecute();

		//Process Actions (it should be run after all the normal process)
		timeStats.start("Process Actions");
		LOGGER.info("Processing Actions");
		ActionHelper.getInstance(androidAnnotationsEnv).process();
		ActionHelper.getInstance(androidAnnotationsEnv).clear();
		timeStats.stop("Process Actions");
		
		return result;
	}
	
	@Override
	protected void generateSources(ProcessResult processResult)
			throws IOException {
				
		timeStats.start("Generate Sources");
		
		int numberOfFiles = processResult.codeModel.countArtifacts() + cachedFiles.size() - cachedFilesGenerated; 
				
		//Generate Actions
		if (!filesCacheHelper.hasCachedFile(DeclexConstant.ACTION) 
			|| !cachedFiles.contains(filesCacheHelper.getFileDetails(DeclexConstant.ACTION))) {
			LOGGER.debug("Generating Action Object");
			if (actions.buildActionsObject()) numberOfFiles++;			
		}
		
		LOGGER.info("Number of files generated by DecleX: {}", numberOfFiles);
		
		if (processResult.codeModel.countArtifacts() > 0) {
			CodeModelGenerator modelGenerator = new DeclexCodeModelGenerator(
				coreVersion, 
				androidAnnotationsEnv.getOptionValue(CodeModelGenerator.OPTION_ENCODING), 
				androidAnnotationsEnv
			);
			modelGenerator.generate(processResult);
		}
		
		for (FileDetails details : cachedFiles) {	
			if (!details.generated) {
				LOGGER.debug("Generating class from cache: {}", details.className);
				details.generate(androidAnnotationsEnv);
				cachedFilesGenerated++;
			}
		}
		
		timeStats.stop("Generate Sources");
		
		timeStats.start("Save Config");				
		SharedRecords.writeEvents(processingEnv);
		SharedRecords.writeDBModels(processingEnv);				
		timeStats.stop("Save Config");

	}
	
	public static void main(String[] args) {
		System.out.println("DecleX Service");
		
		int i = 0;
		while (i < args.length) {
			
			switch (args[i]) {
			
			case "generate":
				try {
					System.setOut(outputFile(FilesCacheHelper.getExternalCache().getAbsolutePath() + File.separator + "generate.log"));
					
					System.out.println("Running Generate Cache Service");
					FilesCacheHelper.runGenerateSources(5);
				} catch (Throwable e) {
					e.printStackTrace();
					System.exit(1);
				} finally {
					System.out.close();
					System.exit(0);
				}
				break;
			
			case "cache":
				try {
					System.setOut(outputFile(FilesCacheHelper.getExternalCache().getAbsolutePath() + File.separator + "cache.log"));
				
					System.out.println("Running Cache Service");
					FilesCacheHelper.runClassCacheCreation();
				} catch (Throwable e) {
					e.printStackTrace();
					System.exit(1);
				} finally {
					System.out.close();
					System.exit(0);
				}
				break;

			default:
				System.out.println("Unknow argument: " + args[i]);
				break;
			}
			
			i++;
		}
	}
	
	private static PrintStream outputFile(String name) throws FileNotFoundException {
		File file = new File(name);
		if (file.exists()) file.delete();
        return new PrintStream(new BufferedOutputStream(new FileOutputStream(name)));
    }
}
